// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// ReadingList is the predicate function for readinglist builders.
type ReadingList func(*sql.Selector)

// ReleaseWeek is the predicate function for releaseweek builders.
type ReleaseWeek func(*sql.Selector)

// Serie is the predicate function for serie builders.
type Serie func(*sql.Selector)

// StoryArc is the predicate function for storyarc builders.
type StoryArc func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
