// Code generated by ent, DO NOT EDIT.

package readinglist

const (
	// Label holds the string label denoting the readinglist type in the database.
	Label = "reading_list"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the readinglist in the database.
	Table = "reading_lists"
)

// Columns holds all SQL columns for readinglist fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
