// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/morsok/comic-handler/ent/readinglist"
)

// ReadingList is the model entity for the ReadingList schema.
type ReadingList struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReadingList) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case readinglist.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ReadingList", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReadingList fields.
func (rl *ReadingList) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case readinglist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rl.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this ReadingList.
// Note that you need to call ReadingList.Unwrap() before calling this method if this ReadingList
// was returned from a transaction, and the transaction was committed or rolled back.
func (rl *ReadingList) Update() *ReadingListUpdateOne {
	return NewReadingListClient(rl.config).UpdateOne(rl)
}

// Unwrap unwraps the ReadingList entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rl *ReadingList) Unwrap() *ReadingList {
	_tx, ok := rl.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReadingList is not a transactional entity")
	}
	rl.config.driver = _tx.drv
	return rl
}

// String implements the fmt.Stringer.
func (rl *ReadingList) String() string {
	var builder strings.Builder
	builder.WriteString("ReadingList(")
	builder.WriteString(fmt.Sprintf("id=%v", rl.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ReadingLists is a parsable slice of ReadingList.
type ReadingLists []*ReadingList

func (rl ReadingLists) config(cfg config) {
	for _i := range rl {
		rl[_i].config = cfg
	}
}
