// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/morsok/comic-handler/ent/predicate"
	"github.com/morsok/comic-handler/ent/readinglist"
)

// ReadingListQuery is the builder for querying ReadingList entities.
type ReadingListQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.ReadingList
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReadingListQuery builder.
func (rlq *ReadingListQuery) Where(ps ...predicate.ReadingList) *ReadingListQuery {
	rlq.predicates = append(rlq.predicates, ps...)
	return rlq
}

// Limit the number of records to be returned by this query.
func (rlq *ReadingListQuery) Limit(limit int) *ReadingListQuery {
	rlq.ctx.Limit = &limit
	return rlq
}

// Offset to start from.
func (rlq *ReadingListQuery) Offset(offset int) *ReadingListQuery {
	rlq.ctx.Offset = &offset
	return rlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rlq *ReadingListQuery) Unique(unique bool) *ReadingListQuery {
	rlq.ctx.Unique = &unique
	return rlq
}

// Order specifies how the records should be ordered.
func (rlq *ReadingListQuery) Order(o ...OrderFunc) *ReadingListQuery {
	rlq.order = append(rlq.order, o...)
	return rlq
}

// First returns the first ReadingList entity from the query.
// Returns a *NotFoundError when no ReadingList was found.
func (rlq *ReadingListQuery) First(ctx context.Context) (*ReadingList, error) {
	nodes, err := rlq.Limit(1).All(setContextOp(ctx, rlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{readinglist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rlq *ReadingListQuery) FirstX(ctx context.Context) *ReadingList {
	node, err := rlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReadingList ID from the query.
// Returns a *NotFoundError when no ReadingList ID was found.
func (rlq *ReadingListQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rlq.Limit(1).IDs(setContextOp(ctx, rlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{readinglist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rlq *ReadingListQuery) FirstIDX(ctx context.Context) int {
	id, err := rlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReadingList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReadingList entity is found.
// Returns a *NotFoundError when no ReadingList entities are found.
func (rlq *ReadingListQuery) Only(ctx context.Context) (*ReadingList, error) {
	nodes, err := rlq.Limit(2).All(setContextOp(ctx, rlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{readinglist.Label}
	default:
		return nil, &NotSingularError{readinglist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rlq *ReadingListQuery) OnlyX(ctx context.Context) *ReadingList {
	node, err := rlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReadingList ID in the query.
// Returns a *NotSingularError when more than one ReadingList ID is found.
// Returns a *NotFoundError when no entities are found.
func (rlq *ReadingListQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rlq.Limit(2).IDs(setContextOp(ctx, rlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{readinglist.Label}
	default:
		err = &NotSingularError{readinglist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rlq *ReadingListQuery) OnlyIDX(ctx context.Context) int {
	id, err := rlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReadingLists.
func (rlq *ReadingListQuery) All(ctx context.Context) ([]*ReadingList, error) {
	ctx = setContextOp(ctx, rlq.ctx, "All")
	if err := rlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReadingList, *ReadingListQuery]()
	return withInterceptors[[]*ReadingList](ctx, rlq, qr, rlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rlq *ReadingListQuery) AllX(ctx context.Context) []*ReadingList {
	nodes, err := rlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReadingList IDs.
func (rlq *ReadingListQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, rlq.ctx, "IDs")
	if err := rlq.Select(readinglist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rlq *ReadingListQuery) IDsX(ctx context.Context) []int {
	ids, err := rlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rlq *ReadingListQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rlq.ctx, "Count")
	if err := rlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rlq, querierCount[*ReadingListQuery](), rlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rlq *ReadingListQuery) CountX(ctx context.Context) int {
	count, err := rlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rlq *ReadingListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rlq.ctx, "Exist")
	switch _, err := rlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rlq *ReadingListQuery) ExistX(ctx context.Context) bool {
	exist, err := rlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReadingListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rlq *ReadingListQuery) Clone() *ReadingListQuery {
	if rlq == nil {
		return nil
	}
	return &ReadingListQuery{
		config:     rlq.config,
		ctx:        rlq.ctx.Clone(),
		order:      append([]OrderFunc{}, rlq.order...),
		inters:     append([]Interceptor{}, rlq.inters...),
		predicates: append([]predicate.ReadingList{}, rlq.predicates...),
		// clone intermediate query.
		sql:  rlq.sql.Clone(),
		path: rlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (rlq *ReadingListQuery) GroupBy(field string, fields ...string) *ReadingListGroupBy {
	rlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReadingListGroupBy{build: rlq}
	grbuild.flds = &rlq.ctx.Fields
	grbuild.label = readinglist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (rlq *ReadingListQuery) Select(fields ...string) *ReadingListSelect {
	rlq.ctx.Fields = append(rlq.ctx.Fields, fields...)
	sbuild := &ReadingListSelect{ReadingListQuery: rlq}
	sbuild.label = readinglist.Label
	sbuild.flds, sbuild.scan = &rlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReadingListSelect configured with the given aggregations.
func (rlq *ReadingListQuery) Aggregate(fns ...AggregateFunc) *ReadingListSelect {
	return rlq.Select().Aggregate(fns...)
}

func (rlq *ReadingListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rlq); err != nil {
				return err
			}
		}
	}
	for _, f := range rlq.ctx.Fields {
		if !readinglist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rlq.path != nil {
		prev, err := rlq.path(ctx)
		if err != nil {
			return err
		}
		rlq.sql = prev
	}
	return nil
}

func (rlq *ReadingListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReadingList, error) {
	var (
		nodes = []*ReadingList{}
		_spec = rlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReadingList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReadingList{config: rlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rlq *ReadingListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rlq.querySpec()
	_spec.Node.Columns = rlq.ctx.Fields
	if len(rlq.ctx.Fields) > 0 {
		_spec.Unique = rlq.ctx.Unique != nil && *rlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rlq.driver, _spec)
}

func (rlq *ReadingListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   readinglist.Table,
			Columns: readinglist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: readinglist.FieldID,
			},
		},
		From:   rlq.sql,
		Unique: true,
	}
	if unique := rlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, readinglist.FieldID)
		for i := range fields {
			if fields[i] != readinglist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rlq *ReadingListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rlq.driver.Dialect())
	t1 := builder.Table(readinglist.Table)
	columns := rlq.ctx.Fields
	if len(columns) == 0 {
		columns = readinglist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rlq.sql != nil {
		selector = rlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rlq.ctx.Unique != nil && *rlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rlq.predicates {
		p(selector)
	}
	for _, p := range rlq.order {
		p(selector)
	}
	if offset := rlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReadingListGroupBy is the group-by builder for ReadingList entities.
type ReadingListGroupBy struct {
	selector
	build *ReadingListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rlgb *ReadingListGroupBy) Aggregate(fns ...AggregateFunc) *ReadingListGroupBy {
	rlgb.fns = append(rlgb.fns, fns...)
	return rlgb
}

// Scan applies the selector query and scans the result into the given value.
func (rlgb *ReadingListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rlgb.build.ctx, "GroupBy")
	if err := rlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReadingListQuery, *ReadingListGroupBy](ctx, rlgb.build, rlgb, rlgb.build.inters, v)
}

func (rlgb *ReadingListGroupBy) sqlScan(ctx context.Context, root *ReadingListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rlgb.fns))
	for _, fn := range rlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rlgb.flds)+len(rlgb.fns))
		for _, f := range *rlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReadingListSelect is the builder for selecting fields of ReadingList entities.
type ReadingListSelect struct {
	*ReadingListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rls *ReadingListSelect) Aggregate(fns ...AggregateFunc) *ReadingListSelect {
	rls.fns = append(rls.fns, fns...)
	return rls
}

// Scan applies the selector query and scans the result into the given value.
func (rls *ReadingListSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rls.ctx, "Select")
	if err := rls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReadingListQuery, *ReadingListSelect](ctx, rls.ReadingListQuery, rls, rls.inters, v)
}

func (rls *ReadingListSelect) sqlScan(ctx context.Context, root *ReadingListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rls.fns))
	for _, fn := range rls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
