// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/morsok/comic-handler/ent/releaseweek"
)

// ReleaseWeekCreate is the builder for creating a ReleaseWeek entity.
type ReleaseWeekCreate struct {
	config
	mutation *ReleaseWeekMutation
	hooks    []Hook
}

// Mutation returns the ReleaseWeekMutation object of the builder.
func (rwc *ReleaseWeekCreate) Mutation() *ReleaseWeekMutation {
	return rwc.mutation
}

// Save creates the ReleaseWeek in the database.
func (rwc *ReleaseWeekCreate) Save(ctx context.Context) (*ReleaseWeek, error) {
	return withHooks[*ReleaseWeek, ReleaseWeekMutation](ctx, rwc.sqlSave, rwc.mutation, rwc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rwc *ReleaseWeekCreate) SaveX(ctx context.Context) *ReleaseWeek {
	v, err := rwc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rwc *ReleaseWeekCreate) Exec(ctx context.Context) error {
	_, err := rwc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rwc *ReleaseWeekCreate) ExecX(ctx context.Context) {
	if err := rwc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rwc *ReleaseWeekCreate) check() error {
	return nil
}

func (rwc *ReleaseWeekCreate) sqlSave(ctx context.Context) (*ReleaseWeek, error) {
	if err := rwc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rwc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rwc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rwc.mutation.id = &_node.ID
	rwc.mutation.done = true
	return _node, nil
}

func (rwc *ReleaseWeekCreate) createSpec() (*ReleaseWeek, *sqlgraph.CreateSpec) {
	var (
		_node = &ReleaseWeek{config: rwc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: releaseweek.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: releaseweek.FieldID,
			},
		}
	)
	return _node, _spec
}

// ReleaseWeekCreateBulk is the builder for creating many ReleaseWeek entities in bulk.
type ReleaseWeekCreateBulk struct {
	config
	builders []*ReleaseWeekCreate
}

// Save creates the ReleaseWeek entities in the database.
func (rwcb *ReleaseWeekCreateBulk) Save(ctx context.Context) ([]*ReleaseWeek, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rwcb.builders))
	nodes := make([]*ReleaseWeek, len(rwcb.builders))
	mutators := make([]Mutator, len(rwcb.builders))
	for i := range rwcb.builders {
		func(i int, root context.Context) {
			builder := rwcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReleaseWeekMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rwcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rwcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rwcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rwcb *ReleaseWeekCreateBulk) SaveX(ctx context.Context) []*ReleaseWeek {
	v, err := rwcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rwcb *ReleaseWeekCreateBulk) Exec(ctx context.Context) error {
	_, err := rwcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rwcb *ReleaseWeekCreateBulk) ExecX(ctx context.Context) {
	if err := rwcb.Exec(ctx); err != nil {
		panic(err)
	}
}
