// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/morsok/comic-handler/ent/predicate"
	"github.com/morsok/comic-handler/ent/releaseweek"
)

// ReleaseWeekQuery is the builder for querying ReleaseWeek entities.
type ReleaseWeekQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.ReleaseWeek
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReleaseWeekQuery builder.
func (rwq *ReleaseWeekQuery) Where(ps ...predicate.ReleaseWeek) *ReleaseWeekQuery {
	rwq.predicates = append(rwq.predicates, ps...)
	return rwq
}

// Limit the number of records to be returned by this query.
func (rwq *ReleaseWeekQuery) Limit(limit int) *ReleaseWeekQuery {
	rwq.ctx.Limit = &limit
	return rwq
}

// Offset to start from.
func (rwq *ReleaseWeekQuery) Offset(offset int) *ReleaseWeekQuery {
	rwq.ctx.Offset = &offset
	return rwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rwq *ReleaseWeekQuery) Unique(unique bool) *ReleaseWeekQuery {
	rwq.ctx.Unique = &unique
	return rwq
}

// Order specifies how the records should be ordered.
func (rwq *ReleaseWeekQuery) Order(o ...OrderFunc) *ReleaseWeekQuery {
	rwq.order = append(rwq.order, o...)
	return rwq
}

// First returns the first ReleaseWeek entity from the query.
// Returns a *NotFoundError when no ReleaseWeek was found.
func (rwq *ReleaseWeekQuery) First(ctx context.Context) (*ReleaseWeek, error) {
	nodes, err := rwq.Limit(1).All(setContextOp(ctx, rwq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{releaseweek.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) FirstX(ctx context.Context) *ReleaseWeek {
	node, err := rwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReleaseWeek ID from the query.
// Returns a *NotFoundError when no ReleaseWeek ID was found.
func (rwq *ReleaseWeekQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rwq.Limit(1).IDs(setContextOp(ctx, rwq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{releaseweek.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) FirstIDX(ctx context.Context) int {
	id, err := rwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReleaseWeek entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReleaseWeek entity is found.
// Returns a *NotFoundError when no ReleaseWeek entities are found.
func (rwq *ReleaseWeekQuery) Only(ctx context.Context) (*ReleaseWeek, error) {
	nodes, err := rwq.Limit(2).All(setContextOp(ctx, rwq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{releaseweek.Label}
	default:
		return nil, &NotSingularError{releaseweek.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) OnlyX(ctx context.Context) *ReleaseWeek {
	node, err := rwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReleaseWeek ID in the query.
// Returns a *NotSingularError when more than one ReleaseWeek ID is found.
// Returns a *NotFoundError when no entities are found.
func (rwq *ReleaseWeekQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rwq.Limit(2).IDs(setContextOp(ctx, rwq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{releaseweek.Label}
	default:
		err = &NotSingularError{releaseweek.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) OnlyIDX(ctx context.Context) int {
	id, err := rwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReleaseWeeks.
func (rwq *ReleaseWeekQuery) All(ctx context.Context) ([]*ReleaseWeek, error) {
	ctx = setContextOp(ctx, rwq.ctx, "All")
	if err := rwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReleaseWeek, *ReleaseWeekQuery]()
	return withInterceptors[[]*ReleaseWeek](ctx, rwq, qr, rwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) AllX(ctx context.Context) []*ReleaseWeek {
	nodes, err := rwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReleaseWeek IDs.
func (rwq *ReleaseWeekQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, rwq.ctx, "IDs")
	if err := rwq.Select(releaseweek.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) IDsX(ctx context.Context) []int {
	ids, err := rwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rwq *ReleaseWeekQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rwq.ctx, "Count")
	if err := rwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rwq, querierCount[*ReleaseWeekQuery](), rwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) CountX(ctx context.Context) int {
	count, err := rwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rwq *ReleaseWeekQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rwq.ctx, "Exist")
	switch _, err := rwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rwq *ReleaseWeekQuery) ExistX(ctx context.Context) bool {
	exist, err := rwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReleaseWeekQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rwq *ReleaseWeekQuery) Clone() *ReleaseWeekQuery {
	if rwq == nil {
		return nil
	}
	return &ReleaseWeekQuery{
		config:     rwq.config,
		ctx:        rwq.ctx.Clone(),
		order:      append([]OrderFunc{}, rwq.order...),
		inters:     append([]Interceptor{}, rwq.inters...),
		predicates: append([]predicate.ReleaseWeek{}, rwq.predicates...),
		// clone intermediate query.
		sql:  rwq.sql.Clone(),
		path: rwq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (rwq *ReleaseWeekQuery) GroupBy(field string, fields ...string) *ReleaseWeekGroupBy {
	rwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReleaseWeekGroupBy{build: rwq}
	grbuild.flds = &rwq.ctx.Fields
	grbuild.label = releaseweek.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (rwq *ReleaseWeekQuery) Select(fields ...string) *ReleaseWeekSelect {
	rwq.ctx.Fields = append(rwq.ctx.Fields, fields...)
	sbuild := &ReleaseWeekSelect{ReleaseWeekQuery: rwq}
	sbuild.label = releaseweek.Label
	sbuild.flds, sbuild.scan = &rwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReleaseWeekSelect configured with the given aggregations.
func (rwq *ReleaseWeekQuery) Aggregate(fns ...AggregateFunc) *ReleaseWeekSelect {
	return rwq.Select().Aggregate(fns...)
}

func (rwq *ReleaseWeekQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rwq); err != nil {
				return err
			}
		}
	}
	for _, f := range rwq.ctx.Fields {
		if !releaseweek.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rwq.path != nil {
		prev, err := rwq.path(ctx)
		if err != nil {
			return err
		}
		rwq.sql = prev
	}
	return nil
}

func (rwq *ReleaseWeekQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReleaseWeek, error) {
	var (
		nodes = []*ReleaseWeek{}
		_spec = rwq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReleaseWeek).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReleaseWeek{config: rwq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rwq *ReleaseWeekQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rwq.querySpec()
	_spec.Node.Columns = rwq.ctx.Fields
	if len(rwq.ctx.Fields) > 0 {
		_spec.Unique = rwq.ctx.Unique != nil && *rwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rwq.driver, _spec)
}

func (rwq *ReleaseWeekQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   releaseweek.Table,
			Columns: releaseweek.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: releaseweek.FieldID,
			},
		},
		From:   rwq.sql,
		Unique: true,
	}
	if unique := rwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, releaseweek.FieldID)
		for i := range fields {
			if fields[i] != releaseweek.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rwq *ReleaseWeekQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rwq.driver.Dialect())
	t1 := builder.Table(releaseweek.Table)
	columns := rwq.ctx.Fields
	if len(columns) == 0 {
		columns = releaseweek.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rwq.sql != nil {
		selector = rwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rwq.ctx.Unique != nil && *rwq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rwq.predicates {
		p(selector)
	}
	for _, p := range rwq.order {
		p(selector)
	}
	if offset := rwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReleaseWeekGroupBy is the group-by builder for ReleaseWeek entities.
type ReleaseWeekGroupBy struct {
	selector
	build *ReleaseWeekQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rwgb *ReleaseWeekGroupBy) Aggregate(fns ...AggregateFunc) *ReleaseWeekGroupBy {
	rwgb.fns = append(rwgb.fns, fns...)
	return rwgb
}

// Scan applies the selector query and scans the result into the given value.
func (rwgb *ReleaseWeekGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rwgb.build.ctx, "GroupBy")
	if err := rwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReleaseWeekQuery, *ReleaseWeekGroupBy](ctx, rwgb.build, rwgb, rwgb.build.inters, v)
}

func (rwgb *ReleaseWeekGroupBy) sqlScan(ctx context.Context, root *ReleaseWeekQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rwgb.fns))
	for _, fn := range rwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rwgb.flds)+len(rwgb.fns))
		for _, f := range *rwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReleaseWeekSelect is the builder for selecting fields of ReleaseWeek entities.
type ReleaseWeekSelect struct {
	*ReleaseWeekQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rws *ReleaseWeekSelect) Aggregate(fns ...AggregateFunc) *ReleaseWeekSelect {
	rws.fns = append(rws.fns, fns...)
	return rws
}

// Scan applies the selector query and scans the result into the given value.
func (rws *ReleaseWeekSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rws.ctx, "Select")
	if err := rws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReleaseWeekQuery, *ReleaseWeekSelect](ctx, rws.ReleaseWeekQuery, rws, rws.inters, v)
}

func (rws *ReleaseWeekSelect) sqlScan(ctx context.Context, root *ReleaseWeekQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rws.fns))
	for _, fn := range rws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
