// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/morsok/comic-handler/ent/predicate"
	"github.com/morsok/comic-handler/ent/releaseweek"
)

// ReleaseWeekDelete is the builder for deleting a ReleaseWeek entity.
type ReleaseWeekDelete struct {
	config
	hooks    []Hook
	mutation *ReleaseWeekMutation
}

// Where appends a list predicates to the ReleaseWeekDelete builder.
func (rwd *ReleaseWeekDelete) Where(ps ...predicate.ReleaseWeek) *ReleaseWeekDelete {
	rwd.mutation.Where(ps...)
	return rwd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rwd *ReleaseWeekDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ReleaseWeekMutation](ctx, rwd.sqlExec, rwd.mutation, rwd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rwd *ReleaseWeekDelete) ExecX(ctx context.Context) int {
	n, err := rwd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rwd *ReleaseWeekDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: releaseweek.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: releaseweek.FieldID,
			},
		},
	}
	if ps := rwd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rwd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rwd.mutation.done = true
	return affected, err
}

// ReleaseWeekDeleteOne is the builder for deleting a single ReleaseWeek entity.
type ReleaseWeekDeleteOne struct {
	rwd *ReleaseWeekDelete
}

// Where appends a list predicates to the ReleaseWeekDelete builder.
func (rwdo *ReleaseWeekDeleteOne) Where(ps ...predicate.ReleaseWeek) *ReleaseWeekDeleteOne {
	rwdo.rwd.mutation.Where(ps...)
	return rwdo
}

// Exec executes the deletion query.
func (rwdo *ReleaseWeekDeleteOne) Exec(ctx context.Context) error {
	n, err := rwdo.rwd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{releaseweek.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rwdo *ReleaseWeekDeleteOne) ExecX(ctx context.Context) {
	if err := rwdo.Exec(ctx); err != nil {
		panic(err)
	}
}
