// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/morsok/comic-handler/ent/predicate"
	"github.com/morsok/comic-handler/ent/storyarc"
)

// StoryArcDelete is the builder for deleting a StoryArc entity.
type StoryArcDelete struct {
	config
	hooks    []Hook
	mutation *StoryArcMutation
}

// Where appends a list predicates to the StoryArcDelete builder.
func (sad *StoryArcDelete) Where(ps ...predicate.StoryArc) *StoryArcDelete {
	sad.mutation.Where(ps...)
	return sad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sad *StoryArcDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, StoryArcMutation](ctx, sad.sqlExec, sad.mutation, sad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sad *StoryArcDelete) ExecX(ctx context.Context) int {
	n, err := sad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sad *StoryArcDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: storyarc.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: storyarc.FieldID,
			},
		},
	}
	if ps := sad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sad.mutation.done = true
	return affected, err
}

// StoryArcDeleteOne is the builder for deleting a single StoryArc entity.
type StoryArcDeleteOne struct {
	sad *StoryArcDelete
}

// Where appends a list predicates to the StoryArcDelete builder.
func (sado *StoryArcDeleteOne) Where(ps ...predicate.StoryArc) *StoryArcDeleteOne {
	sado.sad.mutation.Where(ps...)
	return sado
}

// Exec executes the deletion query.
func (sado *StoryArcDeleteOne) Exec(ctx context.Context) error {
	n, err := sado.sad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storyarc.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sado *StoryArcDeleteOne) ExecX(ctx context.Context) {
	if err := sado.Exec(ctx); err != nil {
		panic(err)
	}
}
