// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/morsok/comic-handler/ent/storyarc"
)

// StoryArc is the model entity for the StoryArc schema.
type StoryArc struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StoryArc) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storyarc.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type StoryArc", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StoryArc fields.
func (sa *StoryArc) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storyarc.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sa.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this StoryArc.
// Note that you need to call StoryArc.Unwrap() before calling this method if this StoryArc
// was returned from a transaction, and the transaction was committed or rolled back.
func (sa *StoryArc) Update() *StoryArcUpdateOne {
	return NewStoryArcClient(sa.config).UpdateOne(sa)
}

// Unwrap unwraps the StoryArc entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sa *StoryArc) Unwrap() *StoryArc {
	_tx, ok := sa.config.driver.(*txDriver)
	if !ok {
		panic("ent: StoryArc is not a transactional entity")
	}
	sa.config.driver = _tx.drv
	return sa
}

// String implements the fmt.Stringer.
func (sa *StoryArc) String() string {
	var builder strings.Builder
	builder.WriteString("StoryArc(")
	builder.WriteString(fmt.Sprintf("id=%v", sa.ID))
	builder.WriteByte(')')
	return builder.String()
}

// StoryArcs is a parsable slice of StoryArc.
type StoryArcs []*StoryArc

func (sa StoryArcs) config(cfg config) {
	for _i := range sa {
		sa[_i].config = cfg
	}
}
