use axum::{
    extract::Path,
    http::StatusCode,
    response::Json,
    routing::{get, post},
    Router,
};
use serde::{Deserialize, Serialize};
use tower::ServiceBuilder;
use tower_http::{
    cors::CorsLayer,
    services::ServeDir,
    trace::TraceLayer,
};
use tracing_subscriber;

#[derive(Serialize, Deserialize)]
struct Comic {
    id: u32,
    title: String,
    description: String,
}

#[derive(Serialize, Deserialize)]
struct CreateComicRequest {
    title: String,
    description: String,
}

// API Handlers
async fn health_check() -> &'static str {
    "OK"
}

async fn list_comics() -> Json<Vec<Comic>> {
    // Mock data for now
    let comics = vec![
        Comic {
            id: 1,
            title: "The Amazing Spider-Man".to_string(),
            description: "Peter Parker's journey as the friendly neighborhood Spider-Man".to_string(),
        },
        Comic {
            id: 2,
            title: "Batman: The Dark Knight".to_string(),
            description: "Bruce Wayne protects Gotham City from the shadows".to_string(),
        },
        Comic {
            id: 3,
            title: "Wonder Woman".to_string(),
            description: "Diana Prince brings justice and truth to the world".to_string(),
        },
        Comic {
            id: 4,
            title: "The Flash: Speed Force".to_string(),
            description: "Barry Allen races through time to save Central City".to_string(),
        },
        Comic {
            id: 5,
            title: "Superman: Man of Steel".to_string(),
            description: "Clark Kent defends Earth with his incredible powers".to_string(),
        },
        Comic {
            id: 6,
            title: "Green Lantern Corps".to_string(),
            description: "The galactic peacekeepers protect the universe".to_string(),
        },
        Comic {
            id: 7,
            title: "X-Men: First Class".to_string(),
            description: "Mutants unite to protect a world that fears them".to_string(),
        },
        Comic {
            id: 8,
            title: "The Avengers".to_string(),
            description: "Earth's mightiest heroes assemble to face the greatest threats".to_string(),
        },
    ];
    
    Json(comics)
}

async fn get_comic(Path(id): Path<u32>) -> Result<Json<Comic>, StatusCode> {
    // Mock data for now
    if id == 1 {
        Ok(Json(Comic {
            id,
            title: "Sample Comic 1".to_string(),
            description: "A great comic about heroes".to_string(),
        }))
    } else if id == 2 {
        Ok(Json(Comic {
            id,
            title: "Sample Comic 2".to_string(),
            description: "Another amazing story".to_string(),
        }))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}

async fn create_comic(Json(payload): Json<CreateComicRequest>) -> Result<Json<Comic>, StatusCode> {
    // Mock creation - in real app, you'd save to database
    let comic = Comic {
        id: 3, // Would be generated by database
        title: payload.title,
        description: payload.description,
    };
    
    Ok(Json(comic))
}

#[tokio::main]
async fn main() {
    // Initialize tracing for logging
    tracing_subscriber::fmt::init();

    // Create API routes
    let api_routes = Router::new()
        .route("/health", get(health_check))
        .route("/comics", get(list_comics))
        .route("/comics", post(create_comic))
        .route("/comics/:id", get(get_comic));

    // Create the main app
    let app = Router::new()
        .nest("/api", api_routes)
        // Serve static files (Angular frontend) for all non-API routes
        .fallback_service(ServeDir::new("/app/static"))
        .layer(
            ServiceBuilder::new()
                .layer(TraceLayer::new_for_http())
                .layer(CorsLayer::permissive()), // Enable CORS for development
        );

    // Bind to all interfaces on port 9999
    let listener = tokio::net::TcpListener::bind("0.0.0.0:9999")
        .await
        .unwrap();
    
    tracing::info!("🚀 Server starting on http://0.0.0.0:9999");
    tracing::info!("📡 API available at http://0.0.0.0:9999/api");
    tracing::info!("🌐 Frontend served from http://0.0.0.0:9999");
    
    axum::serve(listener, app).await.unwrap();
}
