// Code generated by ent, DO NOT EDIT.

package storyarc

const (
	// Label holds the string label denoting the storyarc type in the database.
	Label = "story_arc"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the storyarc in the database.
	Table = "story_arcs"
)

// Columns holds all SQL columns for storyarc fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
