// Code generated by ent, DO NOT EDIT.

package releaseweek

const (
	// Label holds the string label denoting the releaseweek type in the database.
	Label = "release_week"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the releaseweek in the database.
	Table = "release_weeks"
)

// Columns holds all SQL columns for releaseweek fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
